# Generated by Django 2.1.5 on 2019-01-30 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20190130_0206'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='author',
            field=models.CharField(default='anonymous', max_length=50),
            preserve_default=False,
        ),
    ]
